### ISSUE TITLE
IllegalArgumentException: provider=gps

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#126]
<pre>java.lang.RuntimeException: Unable to create service org.traccar.client.TraccarService: java.lang.IllegalArgumentException: provider=gps
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2061)
at android.app.ActivityThread.access$2500(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1053)
at android.os.Handler.dispatchMessage(Handler.java:130)
at android.os.Looper.loop(SourceFile:351)
at android.app.ActivityThread.main(ActivityThread.java:3826)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:538)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: provider=gps
at android.os.Parcel.readException(Parcel.java:1357)
at android.os.Parcel.readException(Parcel.java:1307)
at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:671)
at android.location.LocationManager._requestLocationUpdates(LocationManager.java:617)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java:481)
at org.traccar.client.PositionProvider.startUpdates(PositionProvider.java:68)
at org.traccar.client.TraccarService.onCreate(TraccarService.java:79)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2051)
... 10 more</pre>

**Comment by tananaev** [comment]
Fixed in #127.
