### ISSUE TITLE
Hidden client on tablet

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#159]
Find a way to open client on tables without phone capabilities.

**Comment by JeffZwolle** [comment]
This would also be helpful for Android-CarNavigationSystems

**Comment by tananaev** [comment]
Good idea about URL in web browser. I'll implement it or some other option if I can find anything.

**Comment by DaveDaveDaveDave** [comment]
Any updates on this?  I'm hopeful, since I'd really like this solution to work.  Great software!
Thanks!

**Comment by tananaev** [comment]
I will try to include it in the next major release.

**Comment by tananaev** [comment]
I have added a URL option for opening the app. You can use link from this page:

https://www.traccar.org/client/

**Comment by guenter1952** [comment]
I know it is closed, but...
And how to use the URL option? I get: only a message that it can be used to open the App, thats all.
I did not succeed with my Xiaomi Mi Max Prime.
I tried 2 different versions of the hidden client. It is visible in the Apps-list but not callable by phone. Telephone is allowed for the app. The number dials and returns a message from the telephone network.

**Comment by guenter1952** [comment]
Bug with client is:

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.traccar.client.hidden/org.traccar.client.hidden.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.MainActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/data/app/org.traccar.client.hidden-1/lib/arm64, /system/lib64, /vendor/lib64]]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2744)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6195)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.MainActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/data/app/org.traccar.client.hidden-1/lib/arm64, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2575)
... 9 more

**Comment by tananaev** [comment]
Please create a separate thread. Never commend on closed threads.
