### ISSUE TITLE
SecurityException reported on Google Play

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#172]
```
java.lang.RuntimeException: Unable to create service org.traccar.client.TrackingService: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
	at android.app.ActivityThread.-wrap4(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.os.Parcel.readException(Parcel.java:1599)
	at android.os.Parcel.readException(Parcel.java:1552)
	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
	at org.traccar.client.SimplePositionProvider.startUpdates(SimplePositionProvider.java:34)
	at org.traccar.client.TrackingController.start(TrackingController.java:85)
	at org.traccar.client.TrackingService.onCreate(TrackingService.java:89)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
	... 8 more
```

**Comment by tananaev** [comment]
Fixed.
