### ISSUE TITLE
 FATAL EXCEPTION: Unable to instantiate receiver org.traccar.client.hidden.DialLaunchReceiver

### ISSUE THREAD

**Issue by horbith** [tananaev/traccar-client-android#174]
Hi,
when trying to show background service by calling 8722227 the app crash (on Samsung Galaxy S6 and emulator) 
See below the log.
I need your help

```
01-05 01:36:39.937 8638-8638/org.traccar.client.hidden E/AndroidRuntime: FATAL EXCEPTION: main
 Process: org.traccar.client.hidden, PID: 8638
 java.lang.RuntimeException: Unable to instantiate receiver org.traccar.client.hidden.DialLaunchReceiver: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.DialLaunchReceiver" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2560)
	 at android.app.ActivityThread.access$1700(ActivityThread.java:144)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:135)
	 at android.app.ActivityThread.main(ActivityThread.java:5221)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at java.lang.reflect.Method.invoke(Method.java:372)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.DialLaunchReceiver" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2555)
	 at android.app.ActivityThread.access$1700(ActivityThread.java:144) 
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
	 at android.os.Handler.dispatchMessage(Handler.java:102) 
	 at android.os.Looper.loop(Looper.java:135) 
	 at android.app.ActivityThread.main(ActivityThread.java:5221) 
	 at java.lang.reflect.Method.invoke(Native Method) 
	 at java.lang.reflect.Method.invoke(Method.java:372) 
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
	Suppressed: java.lang.ClassNotFoundException: org.traccar.client.hidden.DialLaunchReceiver
	 at java.lang.Class.classForName(Native Method)
	 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
	 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 11 more
  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by tananaev** [comment]
How did you compile the project? It looks like package id in your app is wrong.

**Comment by horbith** [comment]
thanks @tananaev  for your quick replay.
I have cloned the project and opened it with android studio then from menu "Run" > "Run 'app'"

**Comment by tananaev** [comment]
Check the package in manifest file. It should be `org.traccar.client`. Not sure why it looks for `org.traccar.client.hidden`. It works fine for me.

**Comment by horbith** [comment]
The package in manifest is org.traccar.client  but in build.gradle was  org.traccar.client.hidden

  productFlavors {
        regular {
            applicationId "org.traccar.client"
            buildConfigField "boolean", "HIDDEN_APP", "false"
        }
        hidden {
            applicationId "org.traccar.client.hidden"
            buildConfigField "boolean", "HIDDEN_APP", "true"
        }
    }

when i change  applicationId  from "org.traccar.client.hidden" to  "org.traccar.client" the problem was resolved
I am still testing
Thanks

**Comment by tananaev** [comment]
As a quick fix you can specify full name for the `DialLaunchReceiver` class in hidden app manifest file.

**Comment by horbith** [comment]
Thanks. working fine
