### ISSUE TITLE
Crash when trying open hidden version by link

### ISSUE THREAD

**Issue by tutugreen** [tananaev/traccar-client-android#321]
Crash when using link to open app.
Dialer 8722227 randomly works, sometimes not (go through to call out without crash / opening the app).
Link open is a quite good idea, but it's looks like not work as except?
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.traccar.client.hidden/org.traccar.client.hidden.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.MainActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/data/app/org.traccar.client.hidden-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.hidden.MainActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client.hidden-1/base.apk"],nativeLibraryDirectories=[/data/app/org.traccar.client.hidden-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2616)
	... 9 more
```

**Comment by tananaev** [comment]
I have fixed the issue.
