### ISSUE TITLE
Investigate crash from Google Play

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#69]
<pre>
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.AssertionError: libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)
at libcore.io.IoBridge.getSocketLocalPort(IoBridge.java:603)
at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:155)
at java.net.Socket.connect(Socket.java:838)
at java.net.Socket.connect(Socket.java:785)
at org.traccar.client.Connection$1.doInBackground(Connection.java:75)
at org.traccar.client.Connection$1.doInBackground(Connection.java:69)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more
Caused by: libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)
at libcore.io.Posix.getsockname(Native Method)
at libcore.io.ForwardingOs.getsockname(ForwardingOs.java:69)
at libcore.io.IoBridge.getSocketLocalPort(IoBridge.java:599)
... 11 more
</pre>

**Comment by tananaev** [comment]
Closing as stale.
